import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SWRConfig } from 'swr';
import { swrConfig } from './lib/swr-config';
import { startupOptimization } from '../scripts/startup-optimization';

// Module-level flag to prevent multiple startup optimizations
let startupOptimized = false;

// Run startup optimization automatically (only once)
if (typeof window === 'undefined' && !startupOptimized) {
  // Only run on server side and only once
  startupOptimized = true;
  startupOptimization().catch(console.error);
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SWRConfig value={swrConfig}>
          {children}
        </SWRConfig>
      </body>
    </html>
  );
}
